import { useEffect, useRef, useState } from "react";
import {
  NotebookText,
  X,
  Sparkles,
  AlertCircle,
  Copy,
  Check,
} from "lucide-react";
import ReactMarkdown from "react-markdown";

const NotesPanel = ({ show, loading, notes, onClose, error }) => {
  const panelRef = useRef(null);
  const [copied, setCopied] = useState(false);
  // Scroll to top whenever new notes load in
  useEffect(() => {
    if (notes && panelRef.current) {
      panelRef.current.scrollTop = 0;
    }
  }, [notes]);

  if (!show && !loading && !error) return null;

  const handleCopy = async () => {
  await navigator.clipboard.writeText(notes);
  setCopied(true);
  setTimeout(() => setCopied(false), 2000); // resets after 2s
};

  return (
    <div className="mt-4 rounded-2xl border border-zinc-800 bg-zinc-950 overflow-hidden shadow-xl shadow-black/40 transition-all duration-300">
      {/* ── Header ── */}
      <div className="flex items-center justify-between px-5 py-3.5 border-b border-zinc-800 bg-zinc-900/60">
        <div className="flex items-center gap-2.5">
          <div className="w-10 h-10 rounded-full bg-violet-500/15 flex items-center justify-center">
            <NotebookText size={16} className="text-violet-400" />
          </div>
          <span className="text-white text-sm font-semibold tracking-wide">
            Notes
          </span>
          <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-violet-500/10 text-violet-400 border border-violet-500/20 tracking-wider">
            Generated by Gemini
          </span>
        </div>
        <div>
          <button
            onClick={onClose}
            className="w-10 h-10 flex items-center justify-center rounded-full text-zinc-500 hover:text-white hover:bg-white/10 transition-colors"
            aria-label="Close notes"
          >
            <X size={16} />
          </button>
        </div>
      </div>

      {/* ── Body ── */}
      <div
        ref={panelRef}
        className="max-h-[520px] overflow-y-auto px-5 py-5 scroll-smooth
          [scrollbar-width:thin] [scrollbar-color:#3f3f46_transparent]"
      >
        {/* Loading state */}
        {loading && (
          <div className="flex flex-col items-center justify-center gap-4 py-14 text-zinc-400">
            <div className="relative">
              <div className="w-10 h-10 rounded-full border-2 border-zinc-700 border-t-red-500 animate-spin" />
              <Sparkles
                size={14}
                className="absolute inset-0 m-auto text-red-400"
              />
            </div>
            <div className="text-center">
              <p className="text-sm font-medium text-zinc-300">
                Analyzing video…
              </p>
              <p className="text-xs text-zinc-600 mt-1">
                This may take a moment for longer videos
              </p>
            </div>
          </div>
        )}

        {/* Error state */}
        {!loading && error && (
          <div className="flex items-start gap-3 px-4 py-3.5 rounded-xl bg-red-500/10 border border-red-500/20">
            <AlertCircle size={16} className="text-red-400 mt-0.5 shrink-0" />
            <div>
              <p className="text-red-400 text-sm font-medium">
                Couldn't load notes
              </p>
              <p className="text-red-400/70 text-xs mt-0.5">{error}</p>
            </div>
          </div>
        )}

        {/* Empty state */}
        {!loading && !error && !notes && (
          <div className="flex flex-col items-center justify-center gap-3 py-14 text-zinc-600">
            <NotebookText size={32} strokeWidth={1.2} />
            <p className="text-sm">No notes available for this video.</p>
          </div>
        )}

        {/* Notes content */}
        {!loading && !error && notes && (
          <div
            className="
              prose prose-sm prose-invert max-w-none
              prose-headings:text-white prose-headings:font-semibold
              prose-h1:text-base prose-h2:text-sm prose-h3:text-sm
              prose-p:text-zinc-300 prose-p:leading-relaxed prose-p:my-2
              prose-li:text-zinc-300 prose-li:my-0.5
              prose-ul:pl-4 prose-ol:pl-4
              prose-strong:text-white prose-strong:font-semibold
              prose-code:text-red-300 prose-code:bg-red-500/10 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-xs
              prose-pre:bg-zinc-900 prose-pre:border prose-pre:border-zinc-800 prose-pre:rounded-xl
              prose-blockquote:border-l-red-500/50 prose-blockquote:text-zinc-400 prose-blockquote:not-italic
              prose-hr:border-zinc-800
              [&>*:first-child]:mt-0 [&>*:last-child]:mb-0 space-y-4
            "
          >
            <div className="flex justify-end mt-3">
              <button
                onClick={handleCopy}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all duration-300
      ${
        copied
          ? "text-emerald-400 border-emerald-500/40 bg-emerald-500/10"
          : "text-zinc-400 border-zinc-700 bg-white/[0.05] hover:text-white hover:border-zinc-500"
      }`}
              >
                {copied ? (
                  <>
                    <Check size={13} /> Copied
                  </>
                ) : (
                  <>
                    <Copy size={13} /> Copy notes
                  </>
                )}
              </button>
            </div>
            <ReactMarkdown>{notes}</ReactMarkdown>
          </div>
        )}
      </div>

      {/* ── Footer (only when notes are shown) ── */}
      {!loading && notes && (
        <div className="px-5 py-3 border-t border-zinc-800/60 bg-zinc-900/40 flex items-center gap-1.5">
          <Sparkles size={11} className="text-zinc-600" />
          <p className="text-[11px] text-zinc-600">
            Generated by Gemini · Content may not be fully accurate
          </p>
        </div>
      )}
    </div>
  );
};

export default NotesPanel;
